"""Initial migration with all models

Revision ID: 60cb24ae2a46
Revises: 
Create Date: 2026-08-10 22:13:53.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '60cb24ae2a46'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('ticker', sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('ticker')
    )
    
    op.create_table('financial_statements',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('period', sa.String(length=20), nullable=False),
        sa.Column('statement_type', sa.String(length=50), nullable=False),
        sa.Column('raw_extracted_data', sa.JSON(), nullable=False),
        sa.Column('source_page_ref', sa.Integer(), nullable=False),
        sa.Column('embedding', Vector(dim=384), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('investment_memos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('thesis', sa.Text(), nullable=True),
        sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('calculated_ratios',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('statement_id', sa.Integer(), nullable=False),
        sa.Column('ratio_name', sa.String(length=50), nullable=False),
        sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column('calculation_formula', sa.Text(), nullable=False),
        sa.Column('computed_by', sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(['statement_id'], ['financial_statements.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('citations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('memo_section_id', sa.Integer(), nullable=True),
        sa.Column('claim_text', sa.Text(), nullable=False),
        sa.Column('source_statement_id', sa.Integer(), nullable=False),
        sa.Column('source_page', sa.Integer(), nullable=False),
        sa.Column('source_line', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['source_statement_id'], ['financial_statements.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('citations')
    op.drop_table('calculated_ratios')
    op.drop_table('investment_memos')
    op.drop_table('financial_statements')
    op.drop_table('companies')
    # ### end Alembic commands ###